"""Add payment notifications table

Revision ID: 0943bb702aa0
Revises: bd9e52c95e72
Create Date: 2025-07-04 18:30:14.626137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0943bb702aa0'
down_revision: Union[str, None] = 'bd9e52c95e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('stripe_event_id', sa.String(), nullable=True),
    sa.Column('stripe_event_type', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('stripe_data', sa.JSON(), nullable=True),
    sa.Column('sent_to_telegram', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_notifications_id'), 'payment_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_payment_notifications_stripe_event_id'), 'payment_notifications', ['stripe_event_id'], unique=True)
    op.drop_table('system_settings')
    op.drop_index('idx_global_ai_settings_key', table_name='global_ai_settings')
    op.drop_table('global_ai_settings')
    op.drop_table('messenger_documents')
    op.drop_index('idx_tasks_agent_id', table_name='tasks')
    op.drop_index('idx_tasks_is_recurring', table_name='tasks')
    op.drop_index('idx_tasks_scheduled_time', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_conversation_ai_settings_thread_id', table_name='conversation_ai_settings')
    op.drop_table('conversation_ai_settings')
    op.drop_index('idx_system_logs_agent', table_name='system_logs')
    op.drop_index('idx_system_logs_level', table_name='system_logs')
    op.drop_index('idx_system_logs_source', table_name='system_logs')
    op.drop_index('idx_system_logs_timestamp', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('sandbox_leads')
    op.drop_index('idx_messages_campaign_id', table_name='messages')
    op.drop_index('idx_messages_direction', table_name='messages')
    op.drop_index('idx_messages_lead_id', table_name='messages')
    op.drop_index('idx_messages_message_type', table_name='messages')
    op.drop_index('idx_messages_received_date', table_name='messages')
    op.drop_index('idx_messages_sender_type', table_name='messages')
    op.drop_index('idx_messages_sent_date', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('idx_messages_thread_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('sandbox_templates')
    op.drop_index('idx_agent_logs_agent_id', table_name='agent_logs')
    op.drop_index('idx_agent_logs_timestamp', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_contact_history_campaign_id', table_name='contact_history')
    op.drop_index('idx_contact_history_contact_type', table_name='contact_history')
    op.drop_index('idx_contact_history_created_at', table_name='contact_history')
    op.drop_index('idx_contact_history_lead_id', table_name='contact_history')
    op.drop_table('contact_history')
    op.drop_index('idx_sandbox_conversations_session_id', table_name='sandbox_conversations')
    op.drop_index('idx_sandbox_conversations_session_order', table_name='sandbox_conversations')
    op.drop_index('ix_sandbox_conversations_id', table_name='sandbox_conversations')
    op.drop_table('sandbox_conversations')
    op.drop_index('idx_agent_interactions_created_at', table_name='agent_interactions')
    op.drop_index('idx_agent_interactions_from_agent_id', table_name='agent_interactions')
    op.drop_index('idx_agent_interactions_to_agent_id', table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agents', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agents', 'leads_generes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agents', 'campagnes_actives',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('agents_name_key', 'agents', type_='unique')
    op.drop_index('idx_agents_name', table_name='agents')
    op.drop_index('idx_agents_status', table_name='agents')
    op.drop_index('idx_agents_type', table_name='agents')
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campaigns', 'target_leads',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_campaigns_name', table_name='campaigns')
    op.drop_index('idx_campaigns_niche_id', table_name='campaigns')
    op.drop_index('idx_campaigns_status', table_name='campaigns')
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.drop_constraint('campaigns_niche_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_constraint('campaigns_created_by_fkey', 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'created_by')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'subject_template')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'message_template')
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index('idx_invoices_invoice_date', table_name='invoices')
    op.drop_index('idx_invoices_invoice_number', table_name='invoices')
    op.drop_index('idx_invoices_lead_id', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_stripe_invoice_id', table_name='invoices')
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=False)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('leads', 'validation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('leads', 'design_strengths',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('leads', 'design_weaknesses',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('idx_leads_company', table_name='leads')
    op.drop_index('idx_leads_contact_status', table_name='leads')
    op.drop_index('idx_leads_email', table_name='leads')
    op.drop_index('idx_leads_niche_id', table_name='leads')
    op.drop_index('idx_leads_score', table_name='leads')
    op.drop_index('idx_leads_site_type', table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_stripe_customer_id', table_name='leads')
    op.drop_index('idx_leads_visual_analysis_date', table_name='leads')
    op.drop_index('idx_leads_visual_score', table_name='leads')
    op.drop_index('idx_leads_website_maturity', table_name='leads')
    op.create_index(op.f('ix_leads_first_name'), 'leads', ['first_name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.drop_constraint('leads_niche_id_fkey', 'leads', type_='foreignkey')
    op.drop_column('leads', 'last_contact_status_update')
    op.drop_column('leads', 'contact_status')
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.alter_column('meeting_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('meeting_outcomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_meeting_outcomes_meeting_id', table_name='meeting_outcomes')
    op.drop_index('idx_meeting_outcomes_outcome_type', table_name='meeting_outcomes')
    op.create_index(op.f('ix_meeting_outcomes_id'), 'meeting_outcomes', ['id'], unique=False)
    op.alter_column('meetings', 'client_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('meetings', 'client_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('meetings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index('idx_meetings_calendar_event_id', table_name='meetings')
    op.drop_index('idx_meetings_lead_id', table_name='meetings')
    op.drop_index('idx_meetings_start_time', table_name='meetings')
    op.drop_index('idx_meetings_status', table_name='meetings')
    op.create_index(op.f('ix_meetings_calendar_event_id'), 'meetings', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_lead_id'), 'meetings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_meetings_start_time'), 'meetings', ['start_time'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.drop_constraint('fk_meetings_lead_id', 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'leads', ['lead_id'], ['id'])
    op.create_index(op.f('ix_messenger_directives_id'), 'messenger_directives', ['id'], unique=False)
    op.alter_column('niches', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('niches', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('niches', 'exploration_depth',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('niches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('niches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_niches_name', table_name='niches')
    op.drop_index('idx_niches_status', table_name='niches')
    op.create_index(op.f('ix_niches_id'), 'niches', ['id'], unique=False)
    op.create_index(op.f('ix_niches_name'), 'niches', ['name'], unique=False)
    op.drop_constraint('niches_created_by_fkey', 'niches', type_='foreignkey')
    op.alter_column('sale_services', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sale_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_sale_services_sale_id', table_name='sale_services')
    op.drop_index('idx_sale_services_status', table_name='sale_services')
    op.create_index(op.f('ix_sale_services_id'), 'sale_services', ['id'], unique=False)
    op.alter_column('sales', 'total_setup_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'total_monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_sales_sale_date', table_name='sales')
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.alter_column('services', 'setup_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'is_bundle',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('services', 'bundle_services',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_stripe_product_sync_id'), 'stripe_product_sync', ['id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_stripe_product_sync_id'), table_name='stripe_product_sync')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('services', 'bundle_services',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('services', 'is_bundle',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('services', 'monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('services', 'setup_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.create_index('idx_sales_sale_date', 'sales', ['sale_date'], unique=False)
    op.alter_column('sales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('sales', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('sales', 'total_monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sales', 'total_setup_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sale_services_id'), table_name='sale_services')
    op.create_index('idx_sale_services_status', 'sale_services', ['status'], unique=False)
    op.create_index('idx_sale_services_sale_id', 'sale_services', ['sale_id'], unique=False)
    op.alter_column('sale_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('sale_services', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.create_foreign_key('niches_created_by_fkey', 'niches', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_niches_name'), table_name='niches')
    op.drop_index(op.f('ix_niches_id'), table_name='niches')
    op.create_index('idx_niches_status', 'niches', ['status'], unique=False)
    op.create_index('idx_niches_name', 'niches', ['name'], unique=False)
    op.alter_column('niches', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('niches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('niches', 'exploration_depth',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('niches', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('niches', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_messenger_directives_id'), table_name='messenger_directives')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key('fk_meetings_lead_id', 'meetings', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_start_time'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_lead_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_calendar_event_id'), table_name='meetings')
    op.create_index('idx_meetings_status', 'meetings', ['status'], unique=False)
    op.create_index('idx_meetings_start_time', 'meetings', ['start_time'], unique=False)
    op.create_index('idx_meetings_lead_id', 'meetings', ['lead_id'], unique=False)
    op.create_index('idx_meetings_calendar_event_id', 'meetings', ['calendar_event_id'], unique=False)
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=True)
    op.alter_column('meetings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meetings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meetings', 'client_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('meetings', 'client_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_meeting_outcomes_id'), table_name='meeting_outcomes')
    op.create_index('idx_meeting_outcomes_outcome_type', 'meeting_outcomes', ['outcome_type'], unique=False)
    op.create_index('idx_meeting_outcomes_meeting_id', 'meeting_outcomes', ['meeting_id'], unique=False)
    op.alter_column('meeting_outcomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('meeting_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.add_column('leads', sa.Column('contact_status', sa.VARCHAR(length=50), server_default=sa.text("'never_contacted'::character varying"), autoincrement=False, nullable=True, comment='Statut actuel du contact avec ce lead'))
    op.add_column('leads', sa.Column('last_contact_status_update', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='Timestamp de la dernière mise à jour du contact_status'))
    op.create_foreign_key('leads_niche_id_fkey', 'leads', 'niches', ['niche_id'], ['id'])
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_first_name'), table_name='leads')
    op.create_index('idx_leads_website_maturity', 'leads', ['website_maturity'], unique=False)
    op.create_index('idx_leads_visual_score', 'leads', ['visual_score'], unique=False)
    op.create_index('idx_leads_visual_analysis_date', 'leads', ['visual_analysis_date'], unique=False)
    op.create_index('idx_leads_stripe_customer_id', 'leads', ['stripe_customer_id'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index('idx_leads_site_type', 'leads', ['site_type'], unique=False)
    op.create_index('idx_leads_score', 'leads', ['score'], unique=False)
    op.create_index('idx_leads_niche_id', 'leads', ['niche_id'], unique=False)
    op.create_index('idx_leads_email', 'leads', ['email'], unique=False)
    op.create_index('idx_leads_contact_status', 'leads', ['contact_status'], unique=False)
    op.create_index('idx_leads_company', 'leads', ['company'], unique=False)
    op.alter_column('leads', 'design_weaknesses',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('leads', 'design_strengths',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('leads', 'validation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'unvalidated'::character varying"),
               existing_nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'new'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.create_index('idx_invoices_stripe_invoice_id', 'invoices', ['stripe_invoice_id'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_lead_id', 'invoices', ['lead_id'], unique=False)
    op.create_index('idx_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('idx_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'EUR'::character varying"),
               existing_nullable=False)
    op.add_column('campaigns', sa.Column('message_template', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('subject_template', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('campaigns_created_by_fkey', 'campaigns', 'users', ['created_by'], ['id'])
    op.create_foreign_key('campaigns_niche_id_fkey', 'campaigns', 'niches', ['niche_id'], ['id'])
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.create_index('idx_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index('idx_campaigns_niche_id', 'campaigns', ['niche_id'], unique=False)
    op.create_index('idx_campaigns_name', 'campaigns', ['name'], unique=False)
    op.alter_column('campaigns', 'target_leads',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.create_index('idx_agents_type', 'agents', ['type'], unique=False)
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index('idx_agents_name', 'agents', ['name'], unique=False)
    op.create_unique_constraint('agents_name_key', 'agents', ['name'])
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('agents', 'campagnes_actives',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('agents', 'leads_generes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('agents', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'inactive'::character varying"),
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('agent_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'sent'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], name='agent_interactions_from_agent_id_fkey'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], name='agent_interactions_to_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_interactions_pkey')
    )
    op.create_index('idx_agent_interactions_to_agent_id', 'agent_interactions', ['to_agent_id'], unique=False)
    op.create_index('idx_agent_interactions_from_agent_id', 'agent_interactions', ['from_agent_id'], unique=False)
    op.create_index('idx_agent_interactions_created_at', 'agent_interactions', ['created_at'], unique=False)
    op.create_table('sandbox_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sandbox_lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('conversation_session_id', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True, comment='Identifiant unique de session de conversation (ex: conv_20250606_1234567)'),
    sa.Column('message_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Ordre chronologique des messages dans la session (1, 2, 3...)'),
    sa.Column('message_type', sa.VARCHAR(length=20), server_default=sa.text("'exchange'::character varying"), autoincrement=False, nullable=True, comment='Type de message: start (premier), user (utilisateur), ai (IA), exchange (échange complet)'),
    sa.ForeignKeyConstraint(['sandbox_lead_id'], ['sandbox_leads.id'], name='sandbox_conversations_sandbox_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sandbox_conversations_pkey')
    )
    op.create_index('ix_sandbox_conversations_id', 'sandbox_conversations', ['id'], unique=False)
    op.create_index('idx_sandbox_conversations_session_order', 'sandbox_conversations', ['conversation_session_id', 'message_order'], unique=False)
    op.create_index('idx_sandbox_conversations_session_id', 'sandbox_conversations', ['conversation_session_id'], unique=False)
    op.create_table('contact_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type de contact : initial, follow_up, response_received, etc.'),
    sa.Column('contact_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Méthode de contact utilisée : email, sms, phone, etc.'),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("contact_method::text = ANY (ARRAY['email'::character varying, 'sms'::character varying, 'phone'::character varying, 'linkedin'::character varying, 'other'::character varying]::text[])", name='chk_contact_method'),
    sa.CheckConstraint("contact_type::text = ANY (ARRAY['initial'::character varying, 'follow_up'::character varying, 'response_received'::character varying, 'status_change'::character varying, 'conversion'::character varying, 'unsubscribe'::character varying]::text[])", name='chk_contact_type'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='contact_history_campaign_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='contact_history_lead_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='contact_history_message_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='contact_history_pkey'),
    comment='Historique de tous les contacts et changements de statut pour chaque lead'
    )
    op.create_index('idx_contact_history_lead_id', 'contact_history', ['lead_id'], unique=False)
    op.create_index('idx_contact_history_created_at', 'contact_history', ['created_at'], unique=False)
    op.create_index('idx_contact_history_contact_type', 'contact_history', ['contact_type'], unique=False)
    op.create_index('idx_contact_history_campaign_id', 'contact_history', ['campaign_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_logs_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_logs_pkey')
    )
    op.create_index('idx_agent_logs_timestamp', 'agent_logs', ['timestamp'], unique=False)
    op.create_index('idx_agent_logs_agent_id', 'agent_logs', ['agent_id'], unique=False)
    op.create_table('sandbox_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sandbox_templates_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lead_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reply_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reply_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(), server_default=sa.text("'outbound'::character varying"), autoincrement=False, nullable=True, comment='Direction du message: inbound (reçu) ou outbound (envoyé)'),
    sa.Column('sender_type', sa.VARCHAR(), server_default=sa.text("'ai'::character varying"), autoincrement=False, nullable=True, comment="Type d'expéditeur: ai (BerinIA), user (utilisateur manuel), lead (prospect)"),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Identifiant de fil de conversation, généralement lead_id pour grouper par conversation'),
    sa.Column('message_type', sa.VARCHAR(), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=True, comment='Type de message: email, sms, whatsapp, etc.'),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment="Nom de l'expéditeur (pour messages entrants)"),
    sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Date de réception (pour messages entrants)'),
    sa.Column('message_id_external', sa.VARCHAR(), autoincrement=False, nullable=True, comment='ID du message dans le système externe (Instantly, Twilio, etc.)'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='messages_campaign_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='messages_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('idx_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_index('idx_messages_sent_date', 'messages', ['sent_date'], unique=False)
    op.create_index('idx_messages_sender_type', 'messages', ['sender_type'], unique=False)
    op.create_index('idx_messages_received_date', 'messages', ['received_date'], unique=False)
    op.create_index('idx_messages_message_type', 'messages', ['message_type'], unique=False)
    op.create_index('idx_messages_lead_id', 'messages', ['lead_id'], unique=False)
    op.create_index('idx_messages_direction', 'messages', ['direction'], unique=False)
    op.create_index('idx_messages_campaign_id', 'messages', ['campaign_id'], unique=False)
    op.create_table('sandbox_leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entreprise', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('niche_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validation_status', sa.VARCHAR(), server_default=sa.text("'unvalidated'::character varying"), autoincrement=False, nullable=True),
    sa.Column('last_contact', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visual_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_popup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('popup_removed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('screenshot_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enhanced_screenshot_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visual_analysis_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('site_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visual_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('website_maturity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('design_strengths', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('design_weaknesses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('test_platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('campagne_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('visual_analysis_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sandbox_leads_pkey')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('idx_system_logs_timestamp', 'system_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_system_logs_source', 'system_logs', ['source'], unique=False)
    op.create_index('idx_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('idx_system_logs_agent', 'system_logs', ['agent_name'], unique=False)
    op.create_table('conversation_ai_settings',
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Identifiant unique de la conversation'),
    sa.Column('ai_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True, comment='IA activée (true) ou désactivée (false) pour cette conversation'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', name='conversation_ai_settings_pkey'),
    comment='Paramètres IA spécifiques par conversation'
    )
    op.create_index('idx_conversation_ai_settings_thread_id', 'conversation_ai_settings', ['thread_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('execution_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('recurrence_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='tasks_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_scheduled_time', 'tasks', ['scheduled_time'], unique=False)
    op.create_index('idx_tasks_is_recurring', 'tasks', ['is_recurring'], unique=False)
    op.create_index('idx_tasks_agent_id', 'tasks', ['agent_id'], unique=False)
    op.create_table('messenger_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('extracted_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'admin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='messenger_documents_pkey')
    )
    op.create_table('global_ai_settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Clé du paramètre global'),
    sa.Column('value', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True, comment='Valeur du paramètre (true/false)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='global_ai_settings_pkey'),
    comment='Paramètres IA globaux du système'
    )
    op.create_index('idx_global_ai_settings_key', 'global_ai_settings', ['key'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_editable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey'),
    sa.UniqueConstraint('name', name='system_settings_name_key')
    )
    op.drop_index(op.f('ix_payment_notifications_stripe_event_id'), table_name='payment_notifications')
    op.drop_index(op.f('ix_payment_notifications_id'), table_name='payment_notifications')
    op.drop_table('payment_notifications')
    # ### end Alembic commands ###
